name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      sqlite:
        image: keinos/sqlite3
        options: >-
          --health-cmd "sqlite3 --version"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: sqlite3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: App key and config
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Install Node dependencies
        run: npm ci

      - name: Type check
        run: npm run types

      - name: Lint
        run: npm run lint

      - name: Run tests
        run: php artisan test


